static_library("VoltOS") {
    sources = [
        "VoltOS.c",
        "src/main.c",
        "src/ltc2944.c",
        "src/sht30.c",
    ]

    include_dirs = [
        "//utils/native/lite/include",
        "//third_party/musl/porting/liteos_m/kernel/include",
        "//device/rockchip/rk2206/adapter/incinclude",
        "//device/rockchip/rk2206/sdk_liteos/board/include",
        "inc",
    ]

    deps = [
        "//device/rockchip/hardware:hardware",
    ]
}
